### ISSUE TITLE
When you undeploy it deletes the files, but leaves the directories

### ISSUE THREAD

**Issue by kimptoc** [xebialabs-community/xld-folder-plugin#1]
Thanks for the plugin - worked just fine with my .tgz file :) 

Is there a way to get the directories deleted too?

Not sure what the standard file.Folder does - maybe it does the same with zip files anyway...

More of a nice to have than a real problem.

Cheers.

**Comment by jdewinne** [comment]
I would expect this to work already based on this [line](https://github.com/xebialabs-community/xld-folder-plugin/blob/master/src/main/resources/xld.Folder/unpack_destroy.sh.ftl#L37)
What is the configuration you're using, like plugin version, windows or linux, deployable properties?

**Comment by kimptoc** [comment]
Ok - that will be it.  I set my path to shared true.

I don't suppose this deployable supports the order tag.  I want to deploy a tgz file and then overlay some files onto it.

**Comment by jdewinne** [comment]
That is indeed not supported. If needed, can you please create another issue explaining your use case and/or pull request.
Also you might want to consider reviewing your use case, as it typically conflicts the model based approach and causes the deployment to become less scalable.

**Comment by kimptoc** [comment]
Thanks for the clarifications.  
Indeed, as you say, I seem to be fighting the tool, so probably doing it wrong.

I am thinking either I need to prepare my archive earlier in the build process or see if another tool supports this.

Thanks again.
