### ISSUE TITLE
Support for ordering deployments via createOrder/deleteOrder elements

### ISSUE THREAD

**Issue by kimptoc** [xebialabs-community/xld-folder-plugin#2]
We have a vendor supplied tgz file that we'd like to expand - xld-folder works great for that.
However we need to then overlay some local custom scripts.
Looking to achieve this with 2 deployables that work in the same folder, but we need them to run in a specific order. Hence this request.

I tried to have a go, here - https://github.com/kimptoc/xld-folder-plugin.

It does not work, I guess because its not extending the correct base type.

Trying to now use generic.copiedArtifact, like mentioned here: https://support.xebialabs.com/hc/en-us/community/posts/251240863-How-to-deploy-to-file-deployables-in-a-specific-order

**Comment by jdewinne** [comment]
So how would you overlay these local scripts? Are you maybe using the advanced command plugin for that?
If so, I would strongly advise to create your own plugin. You could perhaps start from the xld-folder-plugin, change the types and add your script as an additional step in the xl-rules.xml file.
That way, you won't need to play with the order values in the deployable (they will be in the rules file), and your overlaying script will be part of the plugin (so not to be copied over and over again). Would that be a better solution for you?

**Comment by kimptoc** [comment]
Hi - I think so, if I understand you correctly.  The new plugin would have a parameter for an overlay folder that needs to be copied too and the plugin could do both things - expand archive and copy over the overlay.

**Comment by jdewinne** [comment]
It could work if you bring them together. This is because each deployable in XLD can only have one attached binary artifact. So your artifact would look like:
`custom.VendorDeployable`: accepts a zip, with the zip containing
    + the tgz, the delivery from the vendor
    + another zip or tgz, being the overlay

And you define a `xl-rule` that extracts the tgz and overlays it with the second part.

**Comment by kimptoc** [comment]
ok.  Presumably that could handle replace placeholders in the overlaid part.

**Comment by jdewinne** [comment]
Closing because inactivity
