### ISSUE TITLE
Support for tar features such as filtering and removing leading directories

### ISSUE THREAD

**Issue by kimptoc** [xebialabs-community/xld-folder-plugin#3]
Some of the tgz files we get from the vendor are not in a directory structure that is immediately useful. So we use some tar options to massage it into a useful form.

Would be handy to do this directly in an XL deployable.

For example, this command

$ tar zxvf {{staging_dir}}/somethingtar.gz --strip-components=3 --directory somedir repository/bin/JAVA/

- the end text filters only files with name matching "repository/bin/JAVA/"
- "--strip-components=3" this removes the first 3 levels of directory hierarchy
- "--directory somedir" this places the result into the given directory - probably covered by the targetDir element.

Cheers,
Chris

**Comment by jdewinne** [comment]
Added strip-components and member filters in [v1.0.0](https://github.com/xebialabs-community/xld-folder-plugin/releases/tag/v1.0.0)
