### ISSUE TITLE
Undeploy more prone to fail than file.Folder is

### ISSUE THREAD

**Issue by kocke01** [xebialabs-community/xld-folder-plugin#4]
I have an artifact with hidden folders and long filenames, and at least on Windows I found that in cases where the file.Folder plugin succeeds, the xld.Folder plug-in does not.
One thing that I think is missing is the -Recurse parameter when the target folder isn't shared.  It's used when it is, but I ran into a problem when not b/c Windows was popping a dialog under the covers on delete due to long file names.  This causes the plug-in to fail: "Windows Powershell is in non-interactive mode.  read and prompt functionality is not available."

This doesn't fix everything.  I still got failures on undeploy when the artifact has hidden/system directories in it.  It throws permission denied failures.  If all I change is the type to file.Folder however, it succeeds.

Not sure what the file.Folder plugin is doing on a delete that xld.Folder is not.

**Comment by jdewinne** [comment]
If the `file.Folder` is working fine, I don't think there's a need to use the `xld.Folder`. The main difference is that the `xld.Folder` will do the extracting of the archive on the target system, while the `file.Folder` will do the extracting on the XLD server.

Would that work for you?

**Comment by kocke01** [comment]
It does - it's just that the xld.Folder has a tendency to be much faster when the archive contains "a lot" of files, especially when it's to the tune of thousands of small files.  I was just noting that the behavior on a windows undeploy was different (in my testing anyway), and maybe something to watch out for.  May not be an easy fix, maybe just a known limitation with the PS method being called.
