### ISSUE TITLE
Error on undeploy on Windows hosts

### ISSUE THREAD

**Issue by brhahlen** [xebialabs-community/xld-folder-plugin#6]
Getting error ```Remove-Item: Windows Powershell is in noninteractive mode. read and prompt is not available```

Can easily be fixed by adding ```-Recurse -Force``` in the "unpack_destroy.ps1", on line 15.

Two questions:

1. Is this something that occurs more often?
2. Is this a satisfactory fix?

If yes to both, I'll update.

**Comment by jdewinne** [comment]
Thanks for bringing this up.

1. No
2. Yes

So feel free to update or send a PR.
